version: 2

updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  labels:
  - dependencies
  - version-updates

- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  labels:
  - dependencies
  - version-updates

