# .goreleaser.yml
---
version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'

brews:
  - commit_author:
      name: goreleasebot
      email: bot@goreleaser.com
    repository:
      owner: jedipunkz
      name: homebrew-miniecs
      branch: main
      token: "{{ .Env.GITHUB_PERSONAL_AUTH_TOKEN }}"
    description: "Miniecs: AWS ECS Login, Exec CLI"
    homepage: "https://github.com/jedipunkz/miniecs"
    install: |
      bin.install "miniecs"
    test: |
      system "${bin}/miniecs --help"
