name: Go-CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
        id: go

      - name: Check Out
        uses: actions/checkout@master

      - name: Cache
        uses: actions/cache@v4.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@master

      - name: Build
        run: go build ./...

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: Test
        run: go test ./... -v

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@master

      - name: Golangci-Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
